dubbo:
  registry:
    address: zookeeper://192.168.153.128:2181
  protocol:
    port: -1
  consumer:
    check: false
  application:
    name: servie_search
spring:
  data:
    solr:
      host: http://192.168.153.128:8983/solr/mycollection
  rabbitmq:
    host: 192.168.153.128
    username: root
    password: root
    virtual-host: /admin
    port: 5672
