spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql:///shop1909?serverTimezone=GMT%2B8
  rabbitmq:
    port: 5672
    host: 192.168.153.128
    virtual-host: /admin
    username: root
    password: root


mybatis-plus:
  mapper-locations: classpath:com/qf/dao/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
dubbo:
  registry:
    address: zookeeper://192.168.153.128:2181
  consumer:
    check: false
  application:
    name: service_goods
  protocol:
    port: -1